# Generated by Django 5.2.1 on 2025-05-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('REVIEWING', 'На рассмотрении'), ('INTERVIEW_SCHEDULED', 'Запланированное собеседование'), ('REJECTED', 'Отклонено'), ('ACCEPTED', 'Принято'), ('ON_HOLD', 'На паузе')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Кандидат'), ('HR_MANAGER', 'HR Менеджер'), ('RESTAURANT_MANAGER', 'Менеджер пицерий'), ('ADMIN', 'Администратор')], default='CANDIDATE', max_length=20),
        ),
        migrations.CreateModel(
            name='QuickApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('resume', models.FileField(upload_to='quick_resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('REVIEWING', 'На рассмотрении'), ('INTERVIEW_SCHEDULED', 'Запланированное собеседование'), ('REJECTED', 'Отклонено'), ('ACCEPTED', 'Принято'), ('ON_HOLD', 'На паузе')], default='NEW', max_length=20)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_applications', to='recruitment.vacancy')),
            ],
        ),
    ]
