# Generated by Django 5.2.1 on 2025-05-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_application_status_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationcomment',
            name='needs_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
