
# Generated by Django 5.2.1 on 2025-05-25 12:19

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_question_answer_test_question_test_testattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
