
# Generated by Django 5.2.1 on 2025-05-25 15:45

from django.db import migrations, models
import django.db.models.deletion

def delete_existing_tests(apps, schema_editor):
    Test = apps.get_model('recruitment', 'Test')
    Test.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_test_is_active'),
    ]

    operations = [
        migrations.RunPython(delete_existing_tests),
        migrations.RemoveField(
            model_name='test',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='test',
            name='position_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='recruitment.positiontype'),
        ),
    ]
