# Generated by Django 5.2.1 on 2025-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_quickapplication_test_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Запланировано'), ('CONFIRMED', 'Подтверждено'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершено'), ('CANCELLED', 'Отменено'), ('RESCHEDULED', 'Перенесено')], default='SCHEDULED', max_length=20),
        ),
    ]
